openapi: 3.0.1
info:
  version: "v1"
  title: Authorization (sub) API
  description: Sub API to handle authorization on a service.
  contact:
    email: support@assembloo.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
    
paths:

##### ROLE DEFINITIONS #####

  /role_definitions/search:
    post:
      summary: Search the role definitions
      tags:
      - RoleDefinitions
      requestBody:
        $ref: "#/components/requestBodies/SearchRequest"
      responses:
        '200':
          $ref: '#/components/responses/SearchResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /role_definitions:
    get:
      summary: List the role definitions
      tags:
      - RoleDefinitions
      parameters:
      - "$ref": "#/components/parameters/pageParam"
      responses:
        '200':
          $ref: '#/components/responses/SearchResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
    post:
      summary: Creates a role definition
      tags:
      - RoleDefinitions
      requestBody:
        $ref: "#/components/requestBodies/RoleDefinitionRequest"
      responses:
        '200':
          description: Role definition successfully created
          content:
            application/json:
              schema:
                type: string
                description: the ID of the created object
        '400':
          description: Bad request
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '422':
          description: Invalid role definition data
  /role_definitions/{roleDefinitionId}:
    parameters:
    - "$ref": "#/components/parameters/roleDefinitionIdParam"
    get:
      summary: Returns a role definition by ID
      tags:
      - RoleDefinitions
      responses:
        '200':
          description: A role definition
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RoleDefinition"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: Authorization not found
    put:
      summary: Updates a role definition
      tags:
      - RoleDefinitions
      requestBody:
        $ref: "#/components/requestBodies/RoleDefinitionRequest"
      responses:
        '200':
          description: Role definition successfully updated
          content:
            application/json:
              schema:
                type: string
                description: the ID of the updated object
        '400':
          description: Bad request
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '422':
          description: Invalid role definition data
    delete:
      summary: Deletes a role definition by ID
      tags:
      - RoleDefinitions
      responses:
        '200':
          description: The role definition was deleted
          content:
            application/json:
              schema:
                type: string
                description: the ID of the deleted object
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: Role definition not found
          
          
##### ROLE ASSIGNMENTS #####

  /role_assignments/search:
    post:
      summary: Search the role assignments
      tags:
      - RoleAssignments
      requestBody:
        $ref: "#/components/requestBodies/SearchRequest"
      responses:
        '200':
          $ref: '#/components/responses/SearchResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /role_assignments:
    get:
      summary: List the role assignments
      tags:
      - RoleAssignments
      parameters:
      - "$ref": "#/components/parameters/pageParam"
      responses:
        '200':
          $ref: '#/components/responses/SearchResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
    post:
      summary: Creates a role assignment
      tags:
      - RoleAssignments
      requestBody:
        $ref: "#/components/requestBodies/RoleAssignmentRequest"
      responses:
        '200':
          description: Role assignment successfully created
          content:
            application/json:
              schema:
                type: string
                description: the ID of the created object
        '400':
          description: Bad request
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '422':
          description: Invalid role assignment data
  /role_assignments/{roleAssignmentId}:
    parameters:
    - "$ref": "#/components/parameters/roleAssignmentIdParam"
    get:
      summary: Returns a role assignment by ID
      tags:
      - RoleAssignments
      responses:
        '200':
          description: A role assignment
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RoleAssignment"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: Role assignment not found
    delete:
      summary: Deletes a role assignment by ID
      tags:
      - RoleAssignments
      responses:
        '200':
          description: The role assignment was deleted
          content:
            application/json:
              schema:
                type: string
                description: the ID of the deleted object
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: Role assignment not found
  
  
components:

  schemas:

    RoleDefinition:
      type: object
      description: a list of roles with their permissions
      properties:
        id:
          type: string
        description:
          type: string
        authorizations:
          type: array
          items:
            type: string
            description: any authorization description, could be a string representation of a wildcard authorization like printer:print:lp123
      required:
      - role_id

    RoleAssignment:
      type: object
      description: List of roles given to users on specific resources
      properties:
        id:
          type: string
        subject_id:
          type: string
          description: user or group this role applies to
        role_id:
          type: string
        resource_id:
          type: string
          description: the path to the resource that the role applies to
      required:
      - subject_id
      - role_id
      - resource_id

    # AssignedPermissions will be defined later if needed
        
  parameters:
    pageParam:
      name: page
      in: query
      description: Page number
      schema:
        type: integer
        minimum: 0
        default: 0
    roleDefinitionIdParam:
      in: path
      name: roleDefinitionId
      schema:
        type: string
      required: true
      description: The role definition id
    roleAssignmentIdParam:
      in: path
      name: roleAssignmentId
      schema:
        type: string
      required: true
      description: The role assignment id

  requestBodies:
    SearchRequest:
      description: The structure to describe the search wanted and what to return
      required: true
      content:
        application/json:
          schema:
            $ref: "https://raw.githubusercontent.com/assembloo/openapi/1.0.0/repository-search.yml#/components/schemas/SearchRequest"
            
    RoleDefinitionRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RoleDefinition"
            
    RoleAssignmentRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RoleAssignment"
    
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
      
    SearchResponse:
      description: A search response of the given object
      content:
        application/json:
          schema:
            $ref: "https://raw.githubusercontent.com/assembloo/openapi/1.0.0/repository-search.yml#/components/schemas/SearchResponse"
  
tags:
  - name: RoleDefinitions
  - name: RoleAssignments

# EOF