openapi: 3.0.1
info:
  version: "v1"
  title: SendMail API
  description: An API to send emails
  contact:
    email: support@assembloo.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
    
paths:
##### SEND #####
  /{serviceId}/send:
    parameters:
    - "$ref": "#/components/parameters/serviceIdParam"
    post:
      summary: Send a mail
      operationId: tta
      tags:
      - SendMail
      requestBody:
        $ref: "#/components/requestBodies/SendMailRequest"
      responses:
        '200':
          description: The mail was sent
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'

##### SMTP SETTINGS #####
  /{serviceId}/settings:
    parameters:
    - "$ref": "#/components/parameters/serviceIdParam"
    get:
      operationId: tt
      summary: Return the smtp settings
      tags:
      - SendMail
      responses:
        '200':
          description: The smtp settings
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'

    put:
      summary: Updates the smtp settings
      operationId: ttaW
      tags:
      - SendMail
      requestBody:
        $ref: "#/components/requestBodies/SmtpSettingsRequest"
      responses:
        '200':
          description: The smtp settings was updated
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'

components:
  schemas:
    SmtpSettings:
      type: object
      description: describes STMP settings
      properties:
        id:
          type: string
        hostName:
          type: string
          description: the name of the smtp server
        portNumber:
          type: integer
          format: int32
          description: the port of the smtp server
        security: 
          $ref: '#/components/schemas/Security'
          description: the type of security          
        authentication: 
          $ref: '#/components/schemas/Authentication'
          description: the type of authentication
      required:
      - hostName
      - portNumber
      - security
      - authentication

    Security: 
      type: string
      enum: 
      - NONE
      - STARTTLS
      - SSL_TLS

    Authentication: 
      type: string
      enum: 
      - NONE
      - NORMAL_PASSWORD
      - ENCRYPTED_PASSWORD
      - KERBEROS
      - NTLM
      - OAUTH2

    SendMailRequest:
      type: object
      description: describe the mail to send
      properties:
        smtpSettingsId:
          type: string
        subject:
          type: string
          description: the subject of the mail
        body:
          type: string
          description: the body of the mail
        to:
          type: array
          description: a list of email addresses
          items:
            type: string
        cc:
          type: array
          description: a list of email addresses
          items:
            type: string
            description: the subject of the mail
        bcc:
          type: array
          description: a list of email addresses
          items:
            type: string
            description: the subject of the mail
        attachments:
          type: array
          description: a list of attachment
          items:
            type: string
            description: a Mime base64 encoded string

      required:
      - subject
      - body
      - to

  parameters:
    serviceIdParam:
      in: path
      name: serviceId
      schema:
        type: string
      required: true
      description: The id of the service the smtp sub-service is mounted on

  requestBodies:
    SendMailRequest:
      description: The structure to describe the search wanted and what to return
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/SendMailRequest"

    SmtpSettingsRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/SmtpSettings"
    
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid

    InternalError:
      description: An error has occured

tags:
  - name: SendMail
    description: "A datastore contains one or more tables. A table holds the records that will search on."

security:
  - bearerAuth: []
  
# EOF
